### ISSUE TITLE
Unused Variable in Fast_Mutual_Information.cpp (minor issue)

### ISSUE THREAD

**Issue by ChrisMuir** [matthewjdenny/SpeedReader#1]
Very minor issue. During installation:
```c++
Fast_Mutual_Information.cpp:15:9: warning: unused variable 'num_cols' [-Wunused-variable]
    int num_cols = joint_dist.n_cols;
        ^
1 warning generated.
```
`num_cols` is defined but never used. I'd be happy to remove it in a PR, just let me know.

**Comment by matthewjdenny** [comment]
Hi Chris,

Sorry I totally forgot to respond but this should be fixed! Thanks for the sharp eyes!

Best,
Matt

**Comment by ChrisMuir** [comment]
No problem, thanks for the great package!
